server:
  port: 8089
dubbo:
  application:
    name: mydubboconsumer1
    id: mydubboconsumer1
  ## ProtocolConfig
  protocol:
    id: dubbo
    name: dubbo
    port: 20889
  scan:
    base-packages: com.example.controller


  #多注册中心
  registries:
    registry1:
      address: zookeeper://127.0.0.1:2181

    registry2:
      address: zookeeper://127.0.0.1:2183

#  registry:
#    address: zookeeper://127.0.0.1:2181
#  consumer:
#    validation: true
#    retries: 0
#    filter: dubboLogFilter

