server:
  port: 8083
dubbo:
  application:
    name: mydubboservice1
    id: mydubboservice1
  ## ProtocolConfig
  protocol:
    id: dubbo
    name: dubbo
    port: 20884
    threads: 400
  scan:
    base-packages: com.example.dubbo.provider

#多注册中心
  registries:
    registry1:
      address: zookeeper://127.0.0.1:2181
    registry2:
      address: zookeeper://127.0.0.1:2183
      default: true

#  单个注册中心
#  registry:
#    address: zookeeper://127.0.0.1:2181
#  provider:
#    validation: true
#    filter: dubboLogFilter
